### ISSUE TITLE
Movie duration

### ISSUE THREAD

**Issue by override187** [scakemyer/plugin.video.pulsar#4]
Movie duration show in minutes instead of hours.

**Comment by scakemyer** [comment]
Noticed that also, just switched the skin I was using and somehow thought it was the culprit... Double-checked in Confluence and can confirm. Will update soon enough when fixed, thanks for reporting it.

**Comment by override187** [comment]
I have installed alpha 2 but error is still there?!

**Comment by scakemyer** [comment]
Try clearing your cache, this was such an obvious fix I can't believe it's not working for you.

**Comment by override187** [comment]
I tryed clear cache, even i deleted pulsar and all files manualy and reinstall and still same. Strange

**Comment by override187** [comment]
I was install alpha 3 now and it is OK, thx for fast fix. Keep a good work

**Comment by scakemyer** [comment]
Thanks! Glad it worked
