### ISSUE TITLE
please provide POT file for easier translation

### ISSUE THREAD

**Issue by meijin007** [scakemyer/plugin.video.pulsar#5]
its how it's should work according to gettext...

**Comment by meijin007** [comment]
you can done it using xgettext on the original string.po files (which currently are missing "msgstr") and change the po file to pot file.

**Comment by scakemyer** [comment]
I'll be looking into this to make it easier on translators

**Comment by scakemyer** [comment]
@meijin007 Thanks for the updated translations! Can you check if the changes in v0.9.0 allows you to translate the way you'd like? If not I'd need some more info on POT files and the process you'd prefer.

**Comment by meijin007** [comment]
@scakemyer - Sorry for the delay.
Checked it now. this is perfect. thanks.
but - POT file within the main "languge" folder will make it easier for new langueges to be add.
i will push a pull request with pot file. thanks!!!
