### ISSUE TITLE
Feature request: limit speed after buffer is build

### ISSUE THREAD

**Issue by corrpel** [scakemyer/plugin.video.pulsar#6]
I would like to see the applied configured limit of the speed after the movies starts.
This way we can make the buffer bigger and not waiting to much for a movie to start.
What do you think?

edit: i usually limit speed for better raspberry pi resource optimization. If i leave it without a limit, it becomes unresponsive.

**Comment by peer23peer** [comment]
I see an added value in something like that +1

**Comment by scakemyer** [comment]
That's a very good idea, I've been having the same problem here (not on a raspberry pi, but almost as underpowered device). Will definitely be implementing this shortly, and a little jealous I didn't think about doing it that way ;) Nice one.

**Comment by scakemyer** [comment]
Implemented in 0ed9789 and available in [v0.9.0](https://github.com/scakemyer/plugin.video.pulsar/releases/tag/v0.9.0)
